In [27]:
import random
import numpy as np

In [75]:
experience_memory = []

for i in range(16):
    s_t = s_t = np.full((1, 120, 128, 4),i)
    a_t = i
    r_t = i*100
    s_t1 = s_t = np.full((1, 120, 128, 4),i+1)
    experience_memory.append((s_t, a_t, r_t, s_t1, False))

In [76]:
BATCH_SIZE = 8
minibatch = random.sample(experience_memory, BATCH_SIZE)

In [77]:
len(minibatch)

8

In [78]:
state_t, action_t, reward_t, state_t1, done = zip(*minibatch)

In [79]:
len(state_t)

8

In [80]:
#targets are 10 different q values for the different actions
targets = np.full((len(minibatch),16),99)

In [81]:
action_t

(9, 11, 0, 8, 15, 12, 5, 1)

In [58]:
state_t = np.concatenate(state_t)

In [59]:
state_t.shape

(8, 120, 128, 4)

In [83]:
targets.shape

(8, 16)

In [88]:
targets[range(8), action_t]

array([99, 99, 99, 99, 99, 99, 99, 99])

In [ ]:
targets[range(BATCH_SIZE), action_t] = reward_t + self.GAMMA*np.max(Q_sa, axis=1)*np.invert(done)

In [101]:
tens =np.ones((10,10))
tens

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [103]:
indices = [2,4,6,8]

tens[1,indices] = [10,20,30,40]
tens

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., 10.,  1., 20.,  1., 30.,  1., 40.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [60]:
def summation(*args):
    total=0
    for i in args:
        total += i
    return total
        
        
print(summation(1,2,3,4,5,6))

21


In [61]:
tup = (1,2)
max(*tup)

2