In [ ]:
from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
import gym_super_mario_bros
from gym_super_mario_bros.actions import COMPLEX_MOVEMENT
from keras.models import Sequential
from keras.layers import Dense, Activation

env = gym_super_mario_bros.make('SuperMarioBros-v0')
env = BinarySpaceToDiscreteSpaceEnv(env, COMPLEX_MOVEMENT)

done = True
state_list = list()
for step in range(50):
    if done:
        state = env.reset()
    state, reward, done, info = env.step(env.action_space.sample())
    state_list.append(state)
    
    env.render()


env.close()

Using TensorFlow backend.


In [55]:
from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
import gym_super_mario_bros
from gym_super_mario_bros.actions import COMPLEX_MOVEMENT
from keras.models import Sequential
from keras.layers import Dense, Activation
import random
import numpy as np
env = gym_super_mario_bros.make('SuperMarioBros-v1')
env = BinarySpaceToDiscreteSpaceEnv(env, COMPLEX_MOVEMENT)

memory = [] #initiate a memory which will hold the set of (state, action, reward, next_state,)
model = Sequential() # initialize our neural network which has for input the state and for output a set of Q-values for state-action pairs
model.add(Dense(32, input_shape=(240, 256, 3), activation = 'relu'))
reward = 0
number_episodes = 10

for episode in range(number_episodes):

    
    state = env.reset() #set initial state
    done = False

    for step in range(50000):
        if done == False:
            epsilone = 0.5
            if random.uniform(0, 1) > epsilone : 
                state, reward, done, info = env.step(env.action_space.sample())
            else :
                action_set = model.predict(np.expand_dims(state, axis = 0))
                Q_max = reward + 0.1 * np.argmax(action_set[0])
                greedy_action = np.argmax(action_set[0])
                state, reward, done, info = env.step(greedy_action)
                    
                
    
    env.render()

env.close()
    


KeyError: 131843

In [57]:
action_set


array([[[[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         ...,
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ]],

        [[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         ...,
         [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
           0.      ],
         [ 0.      ,  0.      ,  0.      , ...,  0

In [36]:
env.observation_space.shape

(240, 256, 3)

In [42]:
state

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[240, 208, 176],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [  0,   0,   0]],

       [[240, 208, 176],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[228,  92,  16],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [228,  92,  16]]

In [10]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

In [18]:
state.shape

(240, 256, 3)

In [35]:
env.observation_space

Box(240, 256, 3)

In [39]:
COMPLEX_MOVEMENT

[['NOOP'],
 ['right'],
 ['right', 'A'],
 ['right', 'B'],
 ['right', 'A', 'B'],
 ['A'],
 ['left'],
 ['left', 'A'],
 ['left', 'B'],
 ['left', 'A', 'B'],
 ['down'],
 ['up']]

In [41]:
env.reset

<bound method BinarySpaceToDiscreteSpaceEnv.reset of <BinarySpaceToDiscreteSpaceEnv<TimeLimit<SuperMarioBrosEnv<SuperMarioBros-v2>>>>>

Help on method sample in module gym.spaces.discrete:

sample() method of gym.spaces.discrete.Discrete instance
    Uniformly randomly sample a random element of this space



In [ ]:
class memory

def __init__

In [44]:
# Deep Q-learning Agent
class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = self._build_model()
    def _build_model(self):
        # Neural Net for Deep-Q learning Model
        model = Sequential()
        model.add(Dense(24, input_dim=self.state_size, activation='relu'))
        model.add(Dense(24, activation='relu'))
        model.add(Dense(self.action_size, activation='linear'))
        model.compile(loss='mse',
                      optimizer=Adam(lr=self.learning_rate))
        return model
    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))
    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        act_values = self.model.predict(state)
        return np.argmax(act_values[0])  # returns action
    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            if not done:
              target = reward + self.gamma * \
                       np.amax(self.model.predict(next_state)[0])
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

In [38]:
import keras

ModuleNotFoundError: No module named 'keras'

array([[[104, 136, 252],
        [104, 136, 252],
        [104, 136, 252],
        ...,
        [104, 136, 252],
        [104, 136, 252],
        [104, 136, 252]],

       [[104, 136, 252],
        [104, 136, 252],
        [104, 136, 252],
        ...,
        [104, 136, 252],
        [104, 136, 252],
        [104, 136, 252]],

       [[104, 136, 252],
        [104, 136, 252],
        [104, 136, 252],
        ...,
        [104, 136, 252],
        [104, 136, 252],
        [104, 136, 252]],

       ...,

       [[228,  92,  16],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [228,  92,  16]],

       [[228,  92,  16],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [228,  92,  16]],

       [[228,  92,  16],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [228,  92,  16]]

In [23]:
info

{'coins': 0,
 'flag_get': False,
 'life': 2,
 'score': 0,
 'stage': 1,
 'status': 'small',
 'time': 150,
 'world': 1,
 'x_pos': 576}

In [22]:
env.step.info()

AttributeError: 'function' object has no attribute 'info'

Help on class BinarySpaceToDiscreteSpaceEnv in module nes_py.wrappers.binary_to_discrete_space_env:

class BinarySpaceToDiscreteSpaceEnv(gym.core.Wrapper)
 |  An environment wrapper to convert binary to discrete action space.
 |  
 |  Method resolution order:
 |      BinarySpaceToDiscreteSpaceEnv
 |      gym.core.Wrapper
 |      gym.core.Env
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, env, actions)
 |      Initialize a new binary to discrete action space wrapper.
 |      
 |      Args:
 |          env (gym.Env): the environment to wrap
 |          actions (list): an ordered list of actions (as lists of buttons).
 |              The index of each button list is its discrete coded value
 |      
 |      Returns:
 |          None
 |  
 |  get_action_meanings(self)
 |      Return a list of actions meanings.
 |  
 |  get_keys_to_action(self)
 |      Return the dictionary of keyboard keys to actions.
 |  
 |  reset(self)
 |      Reset the environment and re

In [4]:
from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT
env = gym_super_mario_bros.make('SuperMarioBros-v0')


In [8]:
help(gym_super_mario_bros.actions)

Help on module gym_super_mario_bros.actions in gym_super_mario_bros:

NAME
    gym_super_mario_bros.actions - Static action sets for binary to discrete action space wrappers.

DATA
    COMPLEX_MOVEMENT = [['NOOP'], ['right'], ['right', 'A'], ['right', 'B'...
    RIGHT_ONLY = [['NOOP'], ['right'], ['right', 'A'], ['right', 'B'], ['r...
    SIMPLE_MOVEMENT = [['NOOP'], ['right'], ['right', 'A'], ['right', 'B']...

FILE
    /Users/andour/anaconda3/envs/python3.6/lib/python3.6/site-packages/gym_super_mario_bros/actions.py


