In [ ]:
from tqdm import tqdm
from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
import gym_super_mario_bros
from gym_super_mario_bros.actions import COMPLEX_MOVEMENT
from keras.models import Sequential
from keras.layers import Dense, Activation

env = gym_super_mario_bros.make('SuperMarioBros-v0')
env = BinarySpaceToDiscreteSpaceEnv(env, COMPLEX_MOVEMENT)


#state_list = list()
state = env.reset()
for step in range(5000):
    state, reward, done, info = env.step(env.action_space.sample())
    #state_list.append(state)
    env.render()
env.close()

Using TensorFlow backend.


RecursionError: maximum recursion depth exceeded

In [2]:
from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
import gym_super_mario_bros
from gym_super_mario_bros.actions import COMPLEX_MOVEMENT
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Convolution2D
import random
import numpy as np
from keras import optimizers
from tqdm import tqdm



memory = [] #initiate a memory which will hold the set of (state, action, reward, next_state,)
model = Sequential()
model.add(Convolution2D(32, 8, 8, subsample=(4, 4), input_shape=(240, 256, 3)))
model.add(Activation('relu'))
model.add(Convolution2D(64, 2, 2, subsample=(2, 2)))
model.add(Activation('relu'))
model.add(Convolution2D(64, 3, 3))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dense(len(COMPLEX_MOVEMENT)))
reward = 0
number_episodes = 10
epsilone = 0.5



for episode in range(1,5):
    env = gym_super_mario_bros.make('SuperMarioBros-v0')
    env = BinarySpaceToDiscreteSpaceEnv(env, COMPLEX_MOVEMENT)
    state = env.reset() #set initial state
    
    for step in tqdm(range(500)):
        if random.uniform(0, 1) > epsilone : 
            state, reward, done, info = env.step(env.action_space.sample())
        else :
            action_set = model.predict(np.expand_dims(state, axis = 0))
            Q_max = reward + 0.1 * np.argmax(action_set[0])
            greedy_action = np.argmax(action_set)
            state, reward, done, info = env.step(greedy_action)
        env.render()
    env.close()
    


/Users/andour/anaconda3/envs/python3.6/lib/python3.6/site-packages/ipykernel_launcher.py:15: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (8, 8), input_shape=(240, 256,..., strides=(4, 4))`
  from ipykernel import kernelapp as app
/Users/andour/anaconda3/envs/python3.6/lib/python3.6/site-packages/ipykernel_launcher.py:17: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (2, 2), strides=(2, 2))`
/Users/andour/anaconda3/envs/python3.6/lib/python3.6/site-packages/ipykernel_launcher.py:19: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3))`
100%|██████████| 500/500 [00:06<00:00, 82.52it/s]


In [ ]:
from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
import gym_super_mario_bros
from gym_super_mario_bros.actions import COMPLEX_MOVEMENT
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Convolution2D
import random
import numpy as np
from keras import optimizers
from tqdm import tqdm



memory = [] #initiate a memory which will hold the set of (state, action, reward, next_state,)
model = Sequential()
model.add(Convolution2D(32, 8, 8, subsample=(4, 4), input_shape=(240, 256, 3)))
model.add(Activation('relu'))
model.add(Convolution2D(64, 2, 2, subsample=(2, 2)))
model.add(Activation('relu'))
model.add(Convolution2D(64, 3, 3))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dense(len(COMPLEX_MOVEMENT)))
reward = 0
number_episodes = 10
epsilone = 0.5



for episode in range(1,5):
    env = gym_super_mario_bros.make('SuperMarioBros-v0')
    env = BinarySpaceToDiscreteSpaceEnv(env, COMPLEX_MOVEMENT)
    state = env.reset() #set initial state
    
    for step in tqdm(range(500)):
        if random.uniform(0, 1) > epsilone : 
            state, reward, done, info = env.step(env.action_space.sample())
        else :
            action_set = model.predict(np.expand_dims(state, axis = 0))
            Q_max = reward + 0.1 * np.argmax(action_set[0])
            greedy_action = np.argmax(action_set)
            state, reward, done, info = env.step(greedy_action)
        env.render()
    env.close()
    


In [3]:
import random
type(random.uniform(0,1)

float

In [ ]:
    def construct_q_network(self):
        self.model = Sequential()
        self.model.add(Convolution2D(32, 8, 8, subsample=(4, 4), input_shape=(84, 84, NUM_FRAMES)))
        self.model.add(Activation('relu'))
        self.model.add(Convolution2D(64, 4, 4, subsample=(2, 2)))
        self.model.add(Activation('relu'))
        self.model.add(Convolution2D(64, 3, 3))
        self.model.add(Activation('relu'))
        self.model.add(Flatten())
        self.model.add(Dense(512))
        self.model.add(Activation('relu'))
        self.model.add(Dense(NUM_ACTIONS))

In [34]:
np.shape(np.expand_dims(state, axis = 0))

(1, 240, 256, 3)

In [35]:
np.shape(action_set)

(1, 737280)

In [10]:
greedy_action

49445

In [11]:
action_set


array([[[[   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         [   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         [   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         ...,
         [   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         [   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         [   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ]],

        [[   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         [   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         [   0.      ,    0.      ,    0.      , ...,    0.      ,
             0.      ,    0.      ],
         ...,
         [   0.      ,    0.      

In [4]:
env.action_space

gym.spaces.discrete.Discrete

In [36]:
env.observation_space.shape

(240, 256, 3)

In [42]:
state

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[240, 208, 176],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [  0,   0,   0]],

       [[240, 208, 176],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[228,  92,  16],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [228,  92,  16]]

In [10]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

In [18]:
state.shape

(240, 256, 3)

In [35]:
env.observation_space

Box(240, 256, 3)

In [39]:
COMPLEX_MOVEMENT

[['NOOP'],
 ['right'],
 ['right', 'A'],
 ['right', 'B'],
 ['right', 'A', 'B'],
 ['A'],
 ['left'],
 ['left', 'A'],
 ['left', 'B'],
 ['left', 'A', 'B'],
 ['down'],
 ['up']]

In [41]:
env.reset

<bound method BinarySpaceToDiscreteSpaceEnv.reset of <BinarySpaceToDiscreteSpaceEnv<TimeLimit<SuperMarioBrosEnv<SuperMarioBros-v2>>>>>

Help on method sample in module gym.spaces.discrete:

sample() method of gym.spaces.discrete.Discrete instance
    Uniformly randomly sample a random element of this space



In [ ]:
class memory

def __init__

In [8]:
env.action_space

Discrete(12)

In [6]:
len(COMPLEX_MOVEMENT)

12

In [44]:


# Deep Q-learning Agent
class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = self._build_model()
    def _build_model(self):
        # Neural Net for Deep-Q learning Model
        model = Sequential()
        model.add(Dense(24, input_dim=self.state_size, activation='relu'))
        model.add(Dense(24, activation='relu'))
        model.add(Dense(self.action_size, activation='linear'))
        model.compile(loss='mse',
                      optimizer=Adam(lr=self.learning_rate))
        return model
    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))
    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        act_values = self.model.predict(state)
        return np.argmax(act_values[0])  # returns action
    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            if not done:
              target = reward + self.gamma * \
                       np.amax(self.model.predict(next_state)[0])
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

In [38]:
import keras

ModuleNotFoundError: No module named 'keras'

array([[[104, 136, 252],
        [104, 136, 252],
        [104, 136, 252],
        ...,
        [104, 136, 252],
        [104, 136, 252],
        [104, 136, 252]],

       [[104, 136, 252],
        [104, 136, 252],
        [104, 136, 252],
        ...,
        [104, 136, 252],
        [104, 136, 252],
        [104, 136, 252]],

       [[104, 136, 252],
        [104, 136, 252],
        [104, 136, 252],
        ...,
        [104, 136, 252],
        [104, 136, 252],
        [104, 136, 252]],

       ...,

       [[228,  92,  16],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [228,  92,  16]],

       [[228,  92,  16],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [228,  92,  16]],

       [[228,  92,  16],
        [228,  92,  16],
        [228,  92,  16],
        ...,
        [228,  92,  16],
        [228,  92,  16],
        [228,  92,  16]]

In [23]:
info

{'coins': 0,
 'flag_get': False,
 'life': 2,
 'score': 0,
 'stage': 1,
 'status': 'small',
 'time': 150,
 'world': 1,
 'x_pos': 576}

In [22]:
env.step.info()

AttributeError: 'function' object has no attribute 'info'

Help on class BinarySpaceToDiscreteSpaceEnv in module nes_py.wrappers.binary_to_discrete_space_env:

class BinarySpaceToDiscreteSpaceEnv(gym.core.Wrapper)
 |  An environment wrapper to convert binary to discrete action space.
 |  
 |  Method resolution order:
 |      BinarySpaceToDiscreteSpaceEnv
 |      gym.core.Wrapper
 |      gym.core.Env
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, env, actions)
 |      Initialize a new binary to discrete action space wrapper.
 |      
 |      Args:
 |          env (gym.Env): the environment to wrap
 |          actions (list): an ordered list of actions (as lists of buttons).
 |              The index of each button list is its discrete coded value
 |      
 |      Returns:
 |          None
 |  
 |  get_action_meanings(self)
 |      Return a list of actions meanings.
 |  
 |  get_keys_to_action(self)
 |      Return the dictionary of keyboard keys to actions.
 |  
 |  reset(self)
 |      Reset the environment and re

In [4]:
from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT
env = gym_super_mario_bros.make('SuperMarioBros-v0')


In [8]:
help(gym_super_mario_bros.actions)

Help on module gym_super_mario_bros.actions in gym_super_mario_bros:

NAME
    gym_super_mario_bros.actions - Static action sets for binary to discrete action space wrappers.

DATA
    COMPLEX_MOVEMENT = [['NOOP'], ['right'], ['right', 'A'], ['right', 'B'...
    RIGHT_ONLY = [['NOOP'], ['right'], ['right', 'A'], ['right', 'B'], ['r...
    SIMPLE_MOVEMENT = [['NOOP'], ['right'], ['right', 'A'], ['right', 'B']...

FILE
    /Users/andour/anaconda3/envs/python3.6/lib/python3.6/site-packages/gym_super_mario_bros/actions.py


